version: '3.8'

services:
  web:
    image: ghcr.io/ceferinsoftware/simona-music:latest
    volumes:
      - station_data:/var/azuracast/stations
      - shoutcast2_install:/var/azuracast/servers/shoutcast2
      - geolite_install:/var/azuracast/geoip
      - sftpgo_data:/var/azuracast/sftpgo/persist
      - backups:/var/azuracast/backups
      - tmp_data:/var/azuracast/www_tmp
    environment:
      # Configuración SSL automática
      LETSENCRYPT_HOST: simonamusic.net,www.simonamusic.net
      LETSENCRYPT_EMAIL: eturingcorporation.com@gmail.com
      VIRTUAL_HOST: simonamusic.net,www.simonamusic.net
      # Puertos de producción
      AZURACAST_HTTP_PORT: 80
      AZURACAST_HTTPS_PORT: 443
      AZURACAST_SFTP_PORT: 2022
    env_file: azuracast.env
    ports:
      - "80:80"
      - "443:443"
      - "2022:2022"
      # Puertos para estaciones de radio
      - "8000-8500:8000-8500"
    networks:
      - azuracast
    depends_on:
      - mariadb
      - redis
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "5"

  mariadb:
    image: mariadb:11.4
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --skip-log-bin
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: myself15867D_
      MYSQL_DATABASE: azuracast
      MYSQL_USER: azuracast
      MYSQL_PASSWORD: myself15867D_
    networks:
      - azuracast
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "5"

  redis:
    image: redis:alpine
    sysctls:
      - net.core.somaxconn=65535
    volumes:
      - redis_data:/data
    networks:
      - azuracast
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "5"

volumes:
  db_data: {}
  redis_data: {}
  station_data: {}
  shoutcast2_install: {}
  geolite_install: {}
  sftpgo_data: {}
  backups: {}
  tmp_data: {}

networks:
  azuracast:
    driver: bridge
